# Generated by Django 3.2.13 on 2022-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(blank=True, default='2022/06/17 06:55:58', max_length=1000000),
        ),
    ]
