# Generated by Django 3.2.13 on 2022-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(blank=True, default='2022/06/22 11:42:25', max_length=1000000),
        ),
    ]
