# Generated by Django 3.2.13 on 2022-06-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(blank=True, default='04:07:42', max_length=1000000),
        ),
    ]
