# Generated by Django 3.2.13 on 2022-06-25 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(blank=True, default=datetime.time(16, 9, 47, 502426), max_length=1000000),
        ),
    ]
