# Generated by Django 3.2.13 on 2022-06-25 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 25, 16, 11, 27, 475995), max_length=1000000),
        ),
    ]
