# Generated by Django 3.2.13 on 2022-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('post_image', models.ImageField(upload_to='')),
                ('no_of_likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('following', models.CharField(max_length=1000000)),
                ('followers', models.CharField(max_length=1000000)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=100)),
            ],
        ),
    ]
