# Generated by Django 3.2.13 on 2022-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default='No caption', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='postImages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.CharField(blank=True, default=0, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.CharField(blank=True, default=0, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultprofileimg.png', upload_to='profileImage'),
        ),
    ]
