# Generated by Django 3.2.13 on 2022-06-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(default='defaultprofileimg.png', upload_to='postcardimages'),
        ),
    ]
