# Generated by Django 3.2.13 on 2022-06-19 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81d1cfc2-b214-492d-96d9-f873375b909a'), primary_key=True, serialize=False),
        ),
    ]
