# Generated by Django 3.2.13 on 2022-06-19 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stang',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
