# Generated by Django 3.2.13 on 2022-06-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likestang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('stang_id', models.CharField(max_length=1000000)),
            ],
        ),
    ]
