# Generated by Django 3.2.13 on 2022-06-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_likestang'),
    ]

    operations = [
        migrations.AddField(
            model_name='stang',
            name='number_of_likes',
            field=models.CharField(blank=True, default=0, max_length=1000000),
        ),
    ]
