# Generated by Django 3.2.13 on 2022-06-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_stang_number_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stang',
            name='number_of_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
