# Generated by Django 3.2.13 on 2022-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_alter_stang_number_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_video',
            field=models.FileField(blank=True, upload_to='postvideos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='postImages'),
        ),
    ]
